version: 1
services:
  - type: web
    name: my-node-app
    env: node
    plan: free
    buildCommand: "npm install"  # Command to install dependencies
    startCommand: "npm start"     # Command to start the application
    publishDir: .                  # Use the root or specify a build directory
